// Code generated by ent, DO NOT EDIT.

package fileinfo

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fileinfo type in the database.
	Label = "file_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNodeName holds the string denoting the node_name field in the database.
	FieldNodeName = "node_name"
	// FieldMountPath holds the string denoting the mount_path field in the database.
	FieldMountPath = "mount_path"
	// FieldFileList holds the string denoting the file_list field in the database.
	FieldFileList = "file_list"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the fileinfo in the database.
	Table = "file_infos"
)

// Columns holds all SQL columns for fileinfo fields.
var Columns = []string{
	FieldID,
	FieldNodeName,
	FieldMountPath,
	FieldFileList,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NodeNameValidator is a validator for the "node_name" field. It is called by the builders before save.
	NodeNameValidator func(string) error
	// MountPathValidator is a validator for the "mount_path" field. It is called by the builders before save.
	MountPathValidator func(string) error
	// DefaultFileList holds the default value on creation for the "file_list" field.
	DefaultFileList []string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the FileInfo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNodeName orders the results by the node_name field.
func ByNodeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeName, opts...).ToFunc()
}

// ByMountPath orders the results by the mount_path field.
func ByMountPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMountPath, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
