// Code generated by ent, DO NOT EDIT.

package fileinfo

import (
	"file-sentinel/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLTE(FieldID, id))
}

// NodeName applies equality check predicate on the "node_name" field. It's identical to NodeNameEQ.
func NodeName(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldNodeName, v))
}

// MountPath applies equality check predicate on the "mount_path" field. It's identical to MountPathEQ.
func MountPath(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldMountPath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// NodeNameEQ applies the EQ predicate on the "node_name" field.
func NodeNameEQ(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldNodeName, v))
}

// NodeNameNEQ applies the NEQ predicate on the "node_name" field.
func NodeNameNEQ(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNEQ(FieldNodeName, v))
}

// NodeNameIn applies the In predicate on the "node_name" field.
func NodeNameIn(vs ...string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldIn(FieldNodeName, vs...))
}

// NodeNameNotIn applies the NotIn predicate on the "node_name" field.
func NodeNameNotIn(vs ...string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNotIn(FieldNodeName, vs...))
}

// NodeNameGT applies the GT predicate on the "node_name" field.
func NodeNameGT(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGT(FieldNodeName, v))
}

// NodeNameGTE applies the GTE predicate on the "node_name" field.
func NodeNameGTE(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGTE(FieldNodeName, v))
}

// NodeNameLT applies the LT predicate on the "node_name" field.
func NodeNameLT(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLT(FieldNodeName, v))
}

// NodeNameLTE applies the LTE predicate on the "node_name" field.
func NodeNameLTE(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLTE(FieldNodeName, v))
}

// NodeNameContains applies the Contains predicate on the "node_name" field.
func NodeNameContains(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldContains(FieldNodeName, v))
}

// NodeNameHasPrefix applies the HasPrefix predicate on the "node_name" field.
func NodeNameHasPrefix(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldHasPrefix(FieldNodeName, v))
}

// NodeNameHasSuffix applies the HasSuffix predicate on the "node_name" field.
func NodeNameHasSuffix(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldHasSuffix(FieldNodeName, v))
}

// NodeNameEqualFold applies the EqualFold predicate on the "node_name" field.
func NodeNameEqualFold(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEqualFold(FieldNodeName, v))
}

// NodeNameContainsFold applies the ContainsFold predicate on the "node_name" field.
func NodeNameContainsFold(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldContainsFold(FieldNodeName, v))
}

// MountPathEQ applies the EQ predicate on the "mount_path" field.
func MountPathEQ(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldMountPath, v))
}

// MountPathNEQ applies the NEQ predicate on the "mount_path" field.
func MountPathNEQ(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNEQ(FieldMountPath, v))
}

// MountPathIn applies the In predicate on the "mount_path" field.
func MountPathIn(vs ...string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldIn(FieldMountPath, vs...))
}

// MountPathNotIn applies the NotIn predicate on the "mount_path" field.
func MountPathNotIn(vs ...string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNotIn(FieldMountPath, vs...))
}

// MountPathGT applies the GT predicate on the "mount_path" field.
func MountPathGT(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGT(FieldMountPath, v))
}

// MountPathGTE applies the GTE predicate on the "mount_path" field.
func MountPathGTE(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGTE(FieldMountPath, v))
}

// MountPathLT applies the LT predicate on the "mount_path" field.
func MountPathLT(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLT(FieldMountPath, v))
}

// MountPathLTE applies the LTE predicate on the "mount_path" field.
func MountPathLTE(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLTE(FieldMountPath, v))
}

// MountPathContains applies the Contains predicate on the "mount_path" field.
func MountPathContains(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldContains(FieldMountPath, v))
}

// MountPathHasPrefix applies the HasPrefix predicate on the "mount_path" field.
func MountPathHasPrefix(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldHasPrefix(FieldMountPath, v))
}

// MountPathHasSuffix applies the HasSuffix predicate on the "mount_path" field.
func MountPathHasSuffix(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldHasSuffix(FieldMountPath, v))
}

// MountPathEqualFold applies the EqualFold predicate on the "mount_path" field.
func MountPathEqualFold(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEqualFold(FieldMountPath, v))
}

// MountPathContainsFold applies the ContainsFold predicate on the "mount_path" field.
func MountPathContainsFold(v string) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldContainsFold(FieldMountPath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FileInfo {
	return predicate.FileInfo(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FileInfo) predicate.FileInfo {
	return predicate.FileInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FileInfo) predicate.FileInfo {
	return predicate.FileInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FileInfo) predicate.FileInfo {
	return predicate.FileInfo(sql.NotPredicates(p))
}
