// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FileInfosColumns holds the columns for the "file_infos" table.
	FileInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "node_name", Type: field.TypeString},
		{Name: "mount_path", Type: field.TypeString},
		{Name: "file_list", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// FileInfosTable holds the schema information for the "file_infos" table.
	FileInfosTable = &schema.Table{
		Name:       "file_infos",
		Columns:    FileInfosColumns,
		PrimaryKey: []*schema.Column{FileInfosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FileInfosTable,
	}
)

func init() {
}
