// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"file-sentinel/ent/fileinfo"
	"file-sentinel/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// FileInfoUpdate is the builder for updating FileInfo entities.
type FileInfoUpdate struct {
	config
	hooks    []Hook
	mutation *FileInfoMutation
}

// Where appends a list predicates to the FileInfoUpdate builder.
func (_u *FileInfoUpdate) Where(ps ...predicate.FileInfo) *FileInfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeName sets the "node_name" field.
func (_u *FileInfoUpdate) SetNodeName(v string) *FileInfoUpdate {
	_u.mutation.SetNodeName(v)
	return _u
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (_u *FileInfoUpdate) SetNillableNodeName(v *string) *FileInfoUpdate {
	if v != nil {
		_u.SetNodeName(*v)
	}
	return _u
}

// SetMountPath sets the "mount_path" field.
func (_u *FileInfoUpdate) SetMountPath(v string) *FileInfoUpdate {
	_u.mutation.SetMountPath(v)
	return _u
}

// SetNillableMountPath sets the "mount_path" field if the given value is not nil.
func (_u *FileInfoUpdate) SetNillableMountPath(v *string) *FileInfoUpdate {
	if v != nil {
		_u.SetMountPath(*v)
	}
	return _u
}

// SetFileList sets the "file_list" field.
func (_u *FileInfoUpdate) SetFileList(v []string) *FileInfoUpdate {
	_u.mutation.SetFileList(v)
	return _u
}

// AppendFileList appends value to the "file_list" field.
func (_u *FileInfoUpdate) AppendFileList(v []string) *FileInfoUpdate {
	_u.mutation.AppendFileList(v)
	return _u
}

// Mutation returns the FileInfoMutation object of the builder.
func (_u *FileInfoUpdate) Mutation() *FileInfoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileInfoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileInfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileInfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileInfoUpdate) check() error {
	if v, ok := _u.mutation.NodeName(); ok {
		if err := fileinfo.NodeNameValidator(v); err != nil {
			return &ValidationError{Name: "node_name", err: fmt.Errorf(`ent: validator failed for field "FileInfo.node_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MountPath(); ok {
		if err := fileinfo.MountPathValidator(v); err != nil {
			return &ValidationError{Name: "mount_path", err: fmt.Errorf(`ent: validator failed for field "FileInfo.mount_path": %w`, err)}
		}
	}
	return nil
}

func (_u *FileInfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileinfo.Table, fileinfo.Columns, sqlgraph.NewFieldSpec(fileinfo.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeName(); ok {
		_spec.SetField(fileinfo.FieldNodeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MountPath(); ok {
		_spec.SetField(fileinfo.FieldMountPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileList(); ok {
		_spec.SetField(fileinfo.FieldFileList, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFileList(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, fileinfo.FieldFileList, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileInfoUpdateOne is the builder for updating a single FileInfo entity.
type FileInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileInfoMutation
}

// SetNodeName sets the "node_name" field.
func (_u *FileInfoUpdateOne) SetNodeName(v string) *FileInfoUpdateOne {
	_u.mutation.SetNodeName(v)
	return _u
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (_u *FileInfoUpdateOne) SetNillableNodeName(v *string) *FileInfoUpdateOne {
	if v != nil {
		_u.SetNodeName(*v)
	}
	return _u
}

// SetMountPath sets the "mount_path" field.
func (_u *FileInfoUpdateOne) SetMountPath(v string) *FileInfoUpdateOne {
	_u.mutation.SetMountPath(v)
	return _u
}

// SetNillableMountPath sets the "mount_path" field if the given value is not nil.
func (_u *FileInfoUpdateOne) SetNillableMountPath(v *string) *FileInfoUpdateOne {
	if v != nil {
		_u.SetMountPath(*v)
	}
	return _u
}

// SetFileList sets the "file_list" field.
func (_u *FileInfoUpdateOne) SetFileList(v []string) *FileInfoUpdateOne {
	_u.mutation.SetFileList(v)
	return _u
}

// AppendFileList appends value to the "file_list" field.
func (_u *FileInfoUpdateOne) AppendFileList(v []string) *FileInfoUpdateOne {
	_u.mutation.AppendFileList(v)
	return _u
}

// Mutation returns the FileInfoMutation object of the builder.
func (_u *FileInfoUpdateOne) Mutation() *FileInfoMutation {
	return _u.mutation
}

// Where appends a list predicates to the FileInfoUpdate builder.
func (_u *FileInfoUpdateOne) Where(ps ...predicate.FileInfo) *FileInfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileInfoUpdateOne) Select(field string, fields ...string) *FileInfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FileInfo entity.
func (_u *FileInfoUpdateOne) Save(ctx context.Context) (*FileInfo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileInfoUpdateOne) SaveX(ctx context.Context) *FileInfo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileInfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileInfoUpdateOne) check() error {
	if v, ok := _u.mutation.NodeName(); ok {
		if err := fileinfo.NodeNameValidator(v); err != nil {
			return &ValidationError{Name: "node_name", err: fmt.Errorf(`ent: validator failed for field "FileInfo.node_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MountPath(); ok {
		if err := fileinfo.MountPathValidator(v); err != nil {
			return &ValidationError{Name: "mount_path", err: fmt.Errorf(`ent: validator failed for field "FileInfo.mount_path": %w`, err)}
		}
	}
	return nil
}

func (_u *FileInfoUpdateOne) sqlSave(ctx context.Context) (_node *FileInfo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileinfo.Table, fileinfo.Columns, sqlgraph.NewFieldSpec(fileinfo.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileinfo.FieldID)
		for _, f := range fields {
			if !fileinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fileinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeName(); ok {
		_spec.SetField(fileinfo.FieldNodeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MountPath(); ok {
		_spec.SetField(fileinfo.FieldMountPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileList(); ok {
		_spec.SetField(fileinfo.FieldFileList, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFileList(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, fileinfo.FieldFileList, value)
		})
	}
	_node = &FileInfo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
