// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"file-sentinel/ent/fileinfo"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileInfoCreate is the builder for creating a FileInfo entity.
type FileInfoCreate struct {
	config
	mutation *FileInfoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNodeName sets the "node_name" field.
func (_c *FileInfoCreate) SetNodeName(v string) *FileInfoCreate {
	_c.mutation.SetNodeName(v)
	return _c
}

// SetMountPath sets the "mount_path" field.
func (_c *FileInfoCreate) SetMountPath(v string) *FileInfoCreate {
	_c.mutation.SetMountPath(v)
	return _c
}

// SetFileList sets the "file_list" field.
func (_c *FileInfoCreate) SetFileList(v []string) *FileInfoCreate {
	_c.mutation.SetFileList(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileInfoCreate) SetCreatedAt(v time.Time) *FileInfoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileInfoCreate) SetNillableCreatedAt(v *time.Time) *FileInfoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the FileInfoMutation object of the builder.
func (_c *FileInfoCreate) Mutation() *FileInfoMutation {
	return _c.mutation
}

// Save creates the FileInfo in the database.
func (_c *FileInfoCreate) Save(ctx context.Context) (*FileInfo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileInfoCreate) SaveX(ctx context.Context) *FileInfo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileInfoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileInfoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileInfoCreate) defaults() {
	if _, ok := _c.mutation.FileList(); !ok {
		v := fileinfo.DefaultFileList
		_c.mutation.SetFileList(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := fileinfo.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileInfoCreate) check() error {
	if _, ok := _c.mutation.NodeName(); !ok {
		return &ValidationError{Name: "node_name", err: errors.New(`ent: missing required field "FileInfo.node_name"`)}
	}
	if v, ok := _c.mutation.NodeName(); ok {
		if err := fileinfo.NodeNameValidator(v); err != nil {
			return &ValidationError{Name: "node_name", err: fmt.Errorf(`ent: validator failed for field "FileInfo.node_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MountPath(); !ok {
		return &ValidationError{Name: "mount_path", err: errors.New(`ent: missing required field "FileInfo.mount_path"`)}
	}
	if v, ok := _c.mutation.MountPath(); ok {
		if err := fileinfo.MountPathValidator(v); err != nil {
			return &ValidationError{Name: "mount_path", err: fmt.Errorf(`ent: validator failed for field "FileInfo.mount_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileList(); !ok {
		return &ValidationError{Name: "file_list", err: errors.New(`ent: missing required field "FileInfo.file_list"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FileInfo.created_at"`)}
	}
	return nil
}

func (_c *FileInfoCreate) sqlSave(ctx context.Context) (*FileInfo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileInfoCreate) createSpec() (*FileInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &FileInfo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fileinfo.Table, sqlgraph.NewFieldSpec(fileinfo.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.NodeName(); ok {
		_spec.SetField(fileinfo.FieldNodeName, field.TypeString, value)
		_node.NodeName = value
	}
	if value, ok := _c.mutation.MountPath(); ok {
		_spec.SetField(fileinfo.FieldMountPath, field.TypeString, value)
		_node.MountPath = value
	}
	if value, ok := _c.mutation.FileList(); ok {
		_spec.SetField(fileinfo.FieldFileList, field.TypeJSON, value)
		_node.FileList = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fileinfo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FileInfo.Create().
//		SetNodeName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileInfoUpsert) {
//			SetNodeName(v+v).
//		}).
//		Exec(ctx)
func (_c *FileInfoCreate) OnConflict(opts ...sql.ConflictOption) *FileInfoUpsertOne {
	_c.conflict = opts
	return &FileInfoUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FileInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileInfoCreate) OnConflictColumns(columns ...string) *FileInfoUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileInfoUpsertOne{
		create: _c,
	}
}

type (
	// FileInfoUpsertOne is the builder for "upsert"-ing
	//  one FileInfo node.
	FileInfoUpsertOne struct {
		create *FileInfoCreate
	}

	// FileInfoUpsert is the "OnConflict" setter.
	FileInfoUpsert struct {
		*sql.UpdateSet
	}
)

// SetNodeName sets the "node_name" field.
func (u *FileInfoUpsert) SetNodeName(v string) *FileInfoUpsert {
	u.Set(fileinfo.FieldNodeName, v)
	return u
}

// UpdateNodeName sets the "node_name" field to the value that was provided on create.
func (u *FileInfoUpsert) UpdateNodeName() *FileInfoUpsert {
	u.SetExcluded(fileinfo.FieldNodeName)
	return u
}

// SetMountPath sets the "mount_path" field.
func (u *FileInfoUpsert) SetMountPath(v string) *FileInfoUpsert {
	u.Set(fileinfo.FieldMountPath, v)
	return u
}

// UpdateMountPath sets the "mount_path" field to the value that was provided on create.
func (u *FileInfoUpsert) UpdateMountPath() *FileInfoUpsert {
	u.SetExcluded(fileinfo.FieldMountPath)
	return u
}

// SetFileList sets the "file_list" field.
func (u *FileInfoUpsert) SetFileList(v []string) *FileInfoUpsert {
	u.Set(fileinfo.FieldFileList, v)
	return u
}

// UpdateFileList sets the "file_list" field to the value that was provided on create.
func (u *FileInfoUpsert) UpdateFileList() *FileInfoUpsert {
	u.SetExcluded(fileinfo.FieldFileList)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FileInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FileInfoUpsertOne) UpdateNewValues() *FileInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(fileinfo.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FileInfo.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FileInfoUpsertOne) Ignore() *FileInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileInfoUpsertOne) DoNothing() *FileInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileInfoCreate.OnConflict
// documentation for more info.
func (u *FileInfoUpsertOne) Update(set func(*FileInfoUpsert)) *FileInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetNodeName sets the "node_name" field.
func (u *FileInfoUpsertOne) SetNodeName(v string) *FileInfoUpsertOne {
	return u.Update(func(s *FileInfoUpsert) {
		s.SetNodeName(v)
	})
}

// UpdateNodeName sets the "node_name" field to the value that was provided on create.
func (u *FileInfoUpsertOne) UpdateNodeName() *FileInfoUpsertOne {
	return u.Update(func(s *FileInfoUpsert) {
		s.UpdateNodeName()
	})
}

// SetMountPath sets the "mount_path" field.
func (u *FileInfoUpsertOne) SetMountPath(v string) *FileInfoUpsertOne {
	return u.Update(func(s *FileInfoUpsert) {
		s.SetMountPath(v)
	})
}

// UpdateMountPath sets the "mount_path" field to the value that was provided on create.
func (u *FileInfoUpsertOne) UpdateMountPath() *FileInfoUpsertOne {
	return u.Update(func(s *FileInfoUpsert) {
		s.UpdateMountPath()
	})
}

// SetFileList sets the "file_list" field.
func (u *FileInfoUpsertOne) SetFileList(v []string) *FileInfoUpsertOne {
	return u.Update(func(s *FileInfoUpsert) {
		s.SetFileList(v)
	})
}

// UpdateFileList sets the "file_list" field to the value that was provided on create.
func (u *FileInfoUpsertOne) UpdateFileList() *FileInfoUpsertOne {
	return u.Update(func(s *FileInfoUpsert) {
		s.UpdateFileList()
	})
}

// Exec executes the query.
func (u *FileInfoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileInfoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileInfoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FileInfoUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FileInfoUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FileInfoCreateBulk is the builder for creating many FileInfo entities in bulk.
type FileInfoCreateBulk struct {
	config
	err      error
	builders []*FileInfoCreate
	conflict []sql.ConflictOption
}

// Save creates the FileInfo entities in the database.
func (_c *FileInfoCreateBulk) Save(ctx context.Context) ([]*FileInfo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileInfo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileInfoCreateBulk) SaveX(ctx context.Context) []*FileInfo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileInfoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FileInfo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FileInfoUpsert) {
//			SetNodeName(v+v).
//		}).
//		Exec(ctx)
func (_c *FileInfoCreateBulk) OnConflict(opts ...sql.ConflictOption) *FileInfoUpsertBulk {
	_c.conflict = opts
	return &FileInfoUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FileInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FileInfoCreateBulk) OnConflictColumns(columns ...string) *FileInfoUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FileInfoUpsertBulk{
		create: _c,
	}
}

// FileInfoUpsertBulk is the builder for "upsert"-ing
// a bulk of FileInfo nodes.
type FileInfoUpsertBulk struct {
	create *FileInfoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FileInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FileInfoUpsertBulk) UpdateNewValues() *FileInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(fileinfo.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FileInfo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FileInfoUpsertBulk) Ignore() *FileInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FileInfoUpsertBulk) DoNothing() *FileInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FileInfoCreateBulk.OnConflict
// documentation for more info.
func (u *FileInfoUpsertBulk) Update(set func(*FileInfoUpsert)) *FileInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FileInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetNodeName sets the "node_name" field.
func (u *FileInfoUpsertBulk) SetNodeName(v string) *FileInfoUpsertBulk {
	return u.Update(func(s *FileInfoUpsert) {
		s.SetNodeName(v)
	})
}

// UpdateNodeName sets the "node_name" field to the value that was provided on create.
func (u *FileInfoUpsertBulk) UpdateNodeName() *FileInfoUpsertBulk {
	return u.Update(func(s *FileInfoUpsert) {
		s.UpdateNodeName()
	})
}

// SetMountPath sets the "mount_path" field.
func (u *FileInfoUpsertBulk) SetMountPath(v string) *FileInfoUpsertBulk {
	return u.Update(func(s *FileInfoUpsert) {
		s.SetMountPath(v)
	})
}

// UpdateMountPath sets the "mount_path" field to the value that was provided on create.
func (u *FileInfoUpsertBulk) UpdateMountPath() *FileInfoUpsertBulk {
	return u.Update(func(s *FileInfoUpsert) {
		s.UpdateMountPath()
	})
}

// SetFileList sets the "file_list" field.
func (u *FileInfoUpsertBulk) SetFileList(v []string) *FileInfoUpsertBulk {
	return u.Update(func(s *FileInfoUpsert) {
		s.SetFileList(v)
	})
}

// UpdateFileList sets the "file_list" field to the value that was provided on create.
func (u *FileInfoUpsertBulk) UpdateFileList() *FileInfoUpsertBulk {
	return u.Update(func(s *FileInfoUpsert) {
		s.UpdateFileList()
	})
}

// Exec executes the query.
func (u *FileInfoUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FileInfoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FileInfoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FileInfoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
