// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"file-sentinel/ent/fileinfo"
	"file-sentinel/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileInfoDelete is the builder for deleting a FileInfo entity.
type FileInfoDelete struct {
	config
	hooks    []Hook
	mutation *FileInfoMutation
}

// Where appends a list predicates to the FileInfoDelete builder.
func (_d *FileInfoDelete) Where(ps ...predicate.FileInfo) *FileInfoDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FileInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FileInfoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FileInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fileinfo.Table, sqlgraph.NewFieldSpec(fileinfo.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FileInfoDeleteOne is the builder for deleting a single FileInfo entity.
type FileInfoDeleteOne struct {
	_d *FileInfoDelete
}

// Where appends a list predicates to the FileInfoDelete builder.
func (_d *FileInfoDeleteOne) Where(ps ...predicate.FileInfo) *FileInfoDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FileInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fileinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FileInfoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
