// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"file-sentinel/ent/fileinfo"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FileInfo is the model entity for the FileInfo schema.
type FileInfo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name of the node
	NodeName string `json:"node_name,omitempty"`
	// Mount path of the file
	MountPath string `json:"mount_path,omitempty"`
	// List of files in JSON format
	FileList []string `json:"file_list,omitempty"`
	// Creation time of the record
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileInfo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fileinfo.FieldFileList:
			values[i] = new([]byte)
		case fileinfo.FieldID:
			values[i] = new(sql.NullInt64)
		case fileinfo.FieldNodeName, fileinfo.FieldMountPath:
			values[i] = new(sql.NullString)
		case fileinfo.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileInfo fields.
func (_m *FileInfo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fileinfo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case fileinfo.FieldNodeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_name", values[i])
			} else if value.Valid {
				_m.NodeName = value.String
			}
		case fileinfo.FieldMountPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mount_path", values[i])
			} else if value.Valid {
				_m.MountPath = value.String
			}
		case fileinfo.FieldFileList:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field file_list", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FileList); err != nil {
					return fmt.Errorf("unmarshal field file_list: %w", err)
				}
			}
		case fileinfo.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FileInfo.
// This includes values selected through modifiers, order, etc.
func (_m *FileInfo) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FileInfo.
// Note that you need to call FileInfo.Unwrap() before calling this method if this FileInfo
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FileInfo) Update() *FileInfoUpdateOne {
	return NewFileInfoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FileInfo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FileInfo) Unwrap() *FileInfo {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FileInfo is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FileInfo) String() string {
	var builder strings.Builder
	builder.WriteString("FileInfo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("node_name=")
	builder.WriteString(_m.NodeName)
	builder.WriteString(", ")
	builder.WriteString("mount_path=")
	builder.WriteString(_m.MountPath)
	builder.WriteString(", ")
	builder.WriteString("file_list=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileList))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FileInfos is a parsable slice of FileInfo.
type FileInfos []*FileInfo
