// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"file-sentinel/ent/fileinfo"
	"file-sentinel/ent/predicate"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFileInfo = "FileInfo"
)

// FileInfoMutation represents an operation that mutates the FileInfo nodes in the graph.
type FileInfoMutation struct {
	config
	op              Op
	typ             string
	id              *int
	node_name       *string
	mount_path      *string
	file_list       *[]string
	appendfile_list []string
	created_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*FileInfo, error)
	predicates      []predicate.FileInfo
}

var _ ent.Mutation = (*FileInfoMutation)(nil)

// fileinfoOption allows management of the mutation configuration using functional options.
type fileinfoOption func(*FileInfoMutation)

// newFileInfoMutation creates new mutation for the FileInfo entity.
func newFileInfoMutation(c config, op Op, opts ...fileinfoOption) *FileInfoMutation {
	m := &FileInfoMutation{
		config:        c,
		op:            op,
		typ:           TypeFileInfo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFileInfoID sets the ID field of the mutation.
func withFileInfoID(id int) fileinfoOption {
	return func(m *FileInfoMutation) {
		var (
			err   error
			once  sync.Once
			value *FileInfo
		)
		m.oldValue = func(ctx context.Context) (*FileInfo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().FileInfo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFileInfo sets the old FileInfo of the mutation.
func withFileInfo(node *FileInfo) fileinfoOption {
	return func(m *FileInfoMutation) {
		m.oldValue = func(context.Context) (*FileInfo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FileInfoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FileInfoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FileInfoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FileInfoMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().FileInfo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNodeName sets the "node_name" field.
func (m *FileInfoMutation) SetNodeName(s string) {
	m.node_name = &s
}

// NodeName returns the value of the "node_name" field in the mutation.
func (m *FileInfoMutation) NodeName() (r string, exists bool) {
	v := m.node_name
	if v == nil {
		return
	}
	return *v, true
}

// OldNodeName returns the old "node_name" field's value of the FileInfo entity.
// If the FileInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FileInfoMutation) OldNodeName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNodeName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNodeName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNodeName: %w", err)
	}
	return oldValue.NodeName, nil
}

// ResetNodeName resets all changes to the "node_name" field.
func (m *FileInfoMutation) ResetNodeName() {
	m.node_name = nil
}

// SetMountPath sets the "mount_path" field.
func (m *FileInfoMutation) SetMountPath(s string) {
	m.mount_path = &s
}

// MountPath returns the value of the "mount_path" field in the mutation.
func (m *FileInfoMutation) MountPath() (r string, exists bool) {
	v := m.mount_path
	if v == nil {
		return
	}
	return *v, true
}

// OldMountPath returns the old "mount_path" field's value of the FileInfo entity.
// If the FileInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FileInfoMutation) OldMountPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMountPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMountPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMountPath: %w", err)
	}
	return oldValue.MountPath, nil
}

// ResetMountPath resets all changes to the "mount_path" field.
func (m *FileInfoMutation) ResetMountPath() {
	m.mount_path = nil
}

// SetFileList sets the "file_list" field.
func (m *FileInfoMutation) SetFileList(s []string) {
	m.file_list = &s
	m.appendfile_list = nil
}

// FileList returns the value of the "file_list" field in the mutation.
func (m *FileInfoMutation) FileList() (r []string, exists bool) {
	v := m.file_list
	if v == nil {
		return
	}
	return *v, true
}

// OldFileList returns the old "file_list" field's value of the FileInfo entity.
// If the FileInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FileInfoMutation) OldFileList(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFileList is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFileList requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFileList: %w", err)
	}
	return oldValue.FileList, nil
}

// AppendFileList adds s to the "file_list" field.
func (m *FileInfoMutation) AppendFileList(s []string) {
	m.appendfile_list = append(m.appendfile_list, s...)
}

// AppendedFileList returns the list of values that were appended to the "file_list" field in this mutation.
func (m *FileInfoMutation) AppendedFileList() ([]string, bool) {
	if len(m.appendfile_list) == 0 {
		return nil, false
	}
	return m.appendfile_list, true
}

// ResetFileList resets all changes to the "file_list" field.
func (m *FileInfoMutation) ResetFileList() {
	m.file_list = nil
	m.appendfile_list = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *FileInfoMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *FileInfoMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the FileInfo entity.
// If the FileInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FileInfoMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *FileInfoMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the FileInfoMutation builder.
func (m *FileInfoMutation) Where(ps ...predicate.FileInfo) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FileInfoMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FileInfoMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.FileInfo, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FileInfoMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FileInfoMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (FileInfo).
func (m *FileInfoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FileInfoMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.node_name != nil {
		fields = append(fields, fileinfo.FieldNodeName)
	}
	if m.mount_path != nil {
		fields = append(fields, fileinfo.FieldMountPath)
	}
	if m.file_list != nil {
		fields = append(fields, fileinfo.FieldFileList)
	}
	if m.created_at != nil {
		fields = append(fields, fileinfo.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FileInfoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case fileinfo.FieldNodeName:
		return m.NodeName()
	case fileinfo.FieldMountPath:
		return m.MountPath()
	case fileinfo.FieldFileList:
		return m.FileList()
	case fileinfo.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FileInfoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case fileinfo.FieldNodeName:
		return m.OldNodeName(ctx)
	case fileinfo.FieldMountPath:
		return m.OldMountPath(ctx)
	case fileinfo.FieldFileList:
		return m.OldFileList(ctx)
	case fileinfo.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown FileInfo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FileInfoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case fileinfo.FieldNodeName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNodeName(v)
		return nil
	case fileinfo.FieldMountPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMountPath(v)
		return nil
	case fileinfo.FieldFileList:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFileList(v)
		return nil
	case fileinfo.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown FileInfo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FileInfoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FileInfoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FileInfoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown FileInfo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FileInfoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FileInfoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FileInfoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown FileInfo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FileInfoMutation) ResetField(name string) error {
	switch name {
	case fileinfo.FieldNodeName:
		m.ResetNodeName()
		return nil
	case fileinfo.FieldMountPath:
		m.ResetMountPath()
		return nil
	case fileinfo.FieldFileList:
		m.ResetFileList()
		return nil
	case fileinfo.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown FileInfo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FileInfoMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FileInfoMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FileInfoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FileInfoMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FileInfoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FileInfoMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FileInfoMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown FileInfo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FileInfoMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown FileInfo edge %s", name)
}
