// Code generated by ent, DO NOT EDIT.

package ent

import (
	"file-sentinel/ent/fileinfo"
	"file-sentinel/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileinfoFields := schema.FileInfo{}.Fields()
	_ = fileinfoFields
	// fileinfoDescNodeName is the schema descriptor for node_name field.
	fileinfoDescNodeName := fileinfoFields[0].Descriptor()
	// fileinfo.NodeNameValidator is a validator for the "node_name" field. It is called by the builders before save.
	fileinfo.NodeNameValidator = fileinfoDescNodeName.Validators[0].(func(string) error)
	// fileinfoDescMountPath is the schema descriptor for mount_path field.
	fileinfoDescMountPath := fileinfoFields[1].Descriptor()
	// fileinfo.MountPathValidator is a validator for the "mount_path" field. It is called by the builders before save.
	fileinfo.MountPathValidator = fileinfoDescMountPath.Validators[0].(func(string) error)
	// fileinfoDescFileList is the schema descriptor for file_list field.
	fileinfoDescFileList := fileinfoFields[2].Descriptor()
	// fileinfo.DefaultFileList holds the default value on creation for the file_list field.
	fileinfo.DefaultFileList = fileinfoDescFileList.Default.([]string)
	// fileinfoDescCreatedAt is the schema descriptor for created_at field.
	fileinfoDescCreatedAt := fileinfoFields[3].Descriptor()
	// fileinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	fileinfo.DefaultCreatedAt = fileinfoDescCreatedAt.Default.(func() time.Time)
}
